/*
 * AgentSessionForm.java
 *
 * Created on __DATE__, __TIME__
 */

package sondas.client.inspector.forms;

import java.util.List;


/**
 *
 * @author  __USER__
 */
public class AgentSessionForm extends javax.swing.JDialog 
{
	private List<String> agents;
	private String agent;
	
	/** Creates new form AgentSessionForm */
	public AgentSessionForm(java.awt.Frame parent, boolean modal, List<String> agents) 
	{
		super(parent, modal);
		
		initComponents();
		this.agents=agents;
		setAgents(agents);
		
		setLocationRelativeTo(parent);
		setVisible(true);
	}
	
	public String getAgent(){
		return agent;
	}
	
	private void setAgents(List<String> agents) 
	{
		jList1.setModel(new javax.swing.AbstractListModel() 
		{
			public int getSize() {
				if (AgentSessionForm.this.agents!=null) {
					return AgentSessionForm.this.agents.size();
				} else 
					return 0;
			}

			public Object getElementAt(int i) {
				return AgentSessionForm.this.agents.get(i);
			}
		});
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		bOk = new javax.swing.JButton();
		bCancel = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setModal(true);

		jLabel1.setText("Select agent");

		jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14));
		jLabel2.setForeground(java.awt.Color.red);
		jLabel2.setText("Agents Manager");

		jScrollPane1.setViewportView(jList1);

		bOk.setText("Ok");
		bOk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bOkActionPerformed(evt);
			}
		});

		bCancel.setText("Cancel");
		bCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bCancelActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				110,
																				110,
																				110)
																		.addComponent(
																				jLabel2))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				44,
																				44,
																				44)
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				77,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				153,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				73,
																				73,
																				73)
																		.addComponent(
																				bOk)
																		.addGap(
																				42,
																				42,
																				42)
																		.addComponent(
																				bCancel)))
										.addContainerGap(59, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel2)
										.addGap(29, 29, 29)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																95,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												28, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(bOk)
														.addComponent(bCancel))
										.addGap(23, 23, 23)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {
		this.setVisible(false);	
		dispose();
	}

	private void bOkActionPerformed(java.awt.event.ActionEvent evt) {
		String agent = (String) jList1.getSelectedValue();
		if (agent!=null) {
			this.agent=agent;
			this.setVisible(false);
		}
		dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	/*
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				AgentSessionForm dialog = new AgentSessionForm(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}*/

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton bCancel;
	private javax.swing.JButton bOk;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JList jList1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}