/*
 * CapturesForm.java
 *
 * Created on __DATE__, __TIME__
 */

package sondas.client.inspector.forms;

import java.util.List;

import sondas.client.inspector.ClientException;
import sondas.inspector.connectivity.DispatcherManager;

/**
 *
 * @author  __USER__
 */
public class CapturesForm extends javax.swing.JDialog 
{
	private List<String> captures;
	private DispatcherManager dm;
	private String capture;
	
	/** Creates new form CapturesForm 
	 * @throws ClientException */
	public CapturesForm(java.awt.Frame parent, boolean modal, DispatcherManager dm) throws ClientException {
		super(parent, modal);
		this.dm=dm;
		initComponents();
		setCaptures();
		setLocationRelativeTo(parent);
		setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		bOk = new javax.swing.JButton();
		bCancel = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14));
		jLabel2.setForeground(java.awt.Color.red);
		jLabel2.setText("Captures Manager");

		bOk.setText("Ok");
		bOk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bOkActionPerformed(evt);
			}
		});

		bCancel.setText("Cancel");
		bCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bCancelActionPerformed(evt);
			}
		});

		jScrollPane1.setViewportView(jList1);

		jLabel1.setText("Select capture");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(21, 21, 21).addComponent(
						jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(27, 27,
						27).addComponent(jScrollPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 171,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(104, Short.MAX_VALUE)).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(152,
						Short.MAX_VALUE).addComponent(jLabel2).addGap(134, 134,
						134)).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(135,
						Short.MAX_VALUE).addComponent(bOk).addGap(32, 32, 32)
						.addComponent(bCancel).addGap(117, 117, 117)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				15,
																				15,
																				15)
																		.addComponent(
																				jLabel2)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				66,
																				66,
																				66)
																		.addComponent(
																				jLabel1)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												29, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(bCancel)
														.addComponent(bOk))
										.addGap(21, 21, 21)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {
		this.setVisible(false);	
		dispose();
	}

	private void bOkActionPerformed(java.awt.event.ActionEvent evt) {
		String capture = (String) jList1.getSelectedValue();
		if (capture!=null) {
			this.capture=capture;
			this.setVisible(false);
		}
		dispose();
	}
	
	public String getCapture() {
		return capture;
	}

	
	private void setCaptures() throws ClientException 
	{
		captures = dm.getCaptures();
		/*
		try {
			captures = dm.getCaptures();
		} catch (ClientException e) {
			e.printStackTrace();
			CommonForms.showError(this, e);
		}*/
		
		jList1.setModel(new javax.swing.AbstractListModel() 
		{
			public int getSize() {
				if (CapturesForm.this.captures!=null) {
					return CapturesForm.this.captures.size();
				} else 
					return 0;
			}

			public Object getElementAt(int i) {
				return CapturesForm.this.captures.get(i);
			}
		});
	}
	

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton bCancel;
	private javax.swing.JButton bOk;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JList jList1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}